sonar.projectKey=idaliopessoa_gospelviral
sonar.organization=idaliopessoa
sonar.host.url=https://sonarcloud.io
sonar.sources=apps/web/src,apps/server/src,packages/shared/src
sonar.tests=apps/web/src,apps/server/src,packages/shared/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/__tests__/**
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info,apps/server/coverage/lcov.info,packages/shared/coverage/lcov.info
sonar.sourceEncoding=UTF-8
